### ISSUE TITLE
Liability Disclamer

### ISSUE THREAD

**Issue by nanea808** [nanea808/3rd-project-boot-campers#22]

**Comment by tropical9** [comment]
Liability Disclaimer

The information provided on this website is for general informational purposes only. While we strive to provide accurate information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.

In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.

Through this website you may be able to link to other websites which are not under our control. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.

Every effort is made to keep the website up and running smoothly. However, we take no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.

By using this website, you agree to the terms of this liability disclaimer. If you do not agree with these terms, please do not use this website.
